pipeline {
    agent any

    environment {
        // Creates POSTGRES_SECRET_USR and POSTGRES_SECRET_PSW env vars
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }

    stages {

        stage('Execute tests') {
            steps {
                echo "Running tests..."

                sh """
                    .venv/bin/activate
                    cd "PyTest DQ Framework"
                    pytest tests -v -m "parquet_data" \
                        --db_host="postgres" \
                        --db_port="5432" \
                        --db_name="mydatabase" \
                        --db_user="${POSTGRES_SECRET_USR}" \
                        --db_password="${POSTGRES_SECRET_PSW}"
                """
            }
        }

        stage('Archive Test Report') {
            steps {
                // Archive the entire html_report directory including assets
                archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

                // Publish the HTML report
                publishHTML(target: [
                    allowMissing: false,
                    keepAll: true,
                    reportDir: 'PyTest DQ Framework/html_report',
                    reportFiles: 'index.html',
                    reportName: 'HTML Test Report'
                ])
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the logs for details.'
        }
    }
}
