pipeline {
    agent any

    environment {
        // This will create POSTGRES_SECRET_USR and POSTGRES_SECRET_PSW environment variables
        POSTGRES_SECRET = credentials('jenkins-postgres-credentials')
    }
  stage('Execute tests') {
  }
  stage('Archive Test Report') {
    steps {
        // Archive the entire html_report directory, including assets
        archiveArtifacts artifacts: 'PyTest DQ Framework/html_report/**', allowEmptyArchive: true

// Publish the HTML report
publishHTML(target: [
            allowMissing: false,  // Fail the pipeline if the report is missing
            keepAll: true,        // Keep all reports from previous runs
            reportDir: 'PyTest DQ Framework/html_report', // Correct directory path
            reportFiles: 'index.html',                          // Entry point file
            reportName: 'HTML Test Report'                      // Display name in Jenkins
])
    }
}
}
